---
- name: Sync the ansible-role-skeleton repository
  ansible.builtin.copy:
    src: "files/role"
    dest: "{{ role_skeleton_location }}"
    mode: 0644
    directory_mode: 0755
  become: yes

- name: Write the role skeleton into the global ansible.cfg
  community.general.ini_file:
    path: "{{ role_skeleton_ansible_cfg_file }}"
    mode: 0644
    section: galaxy
    option: role_skeleton
    value: "{{ role_skeleton_location }}"
  become: yes
