---

- name: Create directory structure
  ansible.builtin.file:
    path: "{{ ansible_role_skeleton_location }}/{{ item.path }}"
    mode: 0755
    state: directory
  loop: "{{
    query('community.general.filetree', 'files/role_skeleton/') |
    selectattr('state', 'eq', 'directory') }}"
  loop_control:
    label: "{{ item.path }}/"
  become: yes

- name: Create normal files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_role_skeleton_location }}/{{ item.path }}"
    mode: 0644
  loop: "{{
    query('community.general.filetree', 'files/role_skeleton/') |
    selectattr('state', 'eq', 'file') |
    rejectattr('path', 'match', '.*\\.tmpl$') }}"
  loop_control:
    label: "{{ item.path }}"
  become: yes

- name: Create files with with additional template vars
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ ansible_role_skeleton_location }}/{{
      item.path.removesuffix('.tmpl') }}"
    mode: 0644
    block_start_string: "[%"
    block_end_string: "%]"
    variable_start_string: "[["
    variable_end_string: "]]"
  loop: "{{
    query('community.general.filetree', 'files/role_skeleton/') |
    selectattr('state', 'eq', 'file') |
    selectattr('path', 'match', '.*\\.tmpl$') }}"
  loop_control:
    label: "{{ item.path }}"
  become: yes

- name: Write the role skeleton into the global ansible.cfg
  community.general.ini_file:
    path: "{{ ansible_role_skeleton_ansible_cfg_file }}"
    mode: 0644
    section: galaxy
    option: role_skeleton
    value: "{{ ansible_role_skeleton_location }}"
  become: yes
