---
- name: Sync the ansible-role-skeleton repository
  git:
    repo: "{{ role_skeleton_repository }}"
    dest: "{{ role_skeleton_location }}"
    version: "{{ role_skeleton_branch }}"
  become: yes

- name: Write the role skeleton into the global ansible.cfg
  ini_file:
    path: "{{ role_skeleton_ansible_cfg_file }}"
    section: galaxy
    option: role_skeleton
    value: "{{ role_skeleton_location }}"
  become: yes
