# -*- mode: ruby -*-
# vi: set ft=ruby :

# Jedes Key-Value-Pair dieses Hashes definiert den Namen und das Box Image einer
# Virtuellen Machine die zum testen der Rolle gestartet werden soll. In dieser
# Liste können je nach Bedarf Zeilen hinzugefügt oder entfernt werden. Der Rest
# des Vagrantfiles sollte nur angepasst werden müssen wenn man ein komplexeres
# Testszenario braucht.
guests = [
    { name: 'ubuntu', box: 'bento/ubuntu-17.04' },
    { name: 'centos', box: 'centos/7' },
#   { name: 'debian', box: 'debian/testing64' },
]

# Bestimme den Namen des Moduls das zu testen ist aus dem Basename des Parent
# Directories des Directories in dem sich der Vagrantfile befindet
test_role = File.basename( File.absolute_path('..') )

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Konfiguration aller Maschinen die in guests definiert sind
    guests.each_with_index do |guest, index|

        config.vm.define "#{test_role}-#{guest[:name]}" do |machine|
            machine.vm.hostname = "#{test_role}-#{guest[:name]}"
            machine.vm.box = guest[:box]
            # Jede Maschine bekommt eine IP im privaten Default Netzwerk von
            # Virtualbox, die sowohl von anderen VMs als auch vom Host aus
            # erreichbar ist. Für komplexere Tests sollte hier wahrscheinlich
            # trotzdem ein anderer Weg gewählt werden
            machine.vm.network 'private_network', type: 'dhcp'

            # Allgemeine Einstellungen die jede Maschine in Virtualbox bekommt.
            # Dieser Bereich kann an die Fähigkeiten des Hosts angepasst werden.
            machine.vm.provider 'virtualbox' do |vbox|
                vbox.name = "ansibe_#{test_role}_#{guest[:name]}"
                vbox.cpus = 2
                vbox.memory = 2048
            end

            # Provisioniere, wenn die letzte Maschine hochgefahren wurde, alle
            # Maschinen mit Ansible. Würde dieser Block außerhalb einer einzigen
            # Maschinendefinition stehen, würde Ansible beim Hochfahren jeder
            # Maschine versuchen alle Maschinen zu konfigurieren
            if index == guests.size - 1
                machine.vm.provision 'ansible', run: 'always' do |ansible|
                    ansible.playbook = 'test.yml'
                    #ansible.verbose = 'vvvv'
                    #ansible.host_key_checking = false
                    ansible.limit = 'all'
                    ansible.sudo = false
                    ansible.extra_vars = {
                        test_role: test_role,
                    }
                end
            end
        end
    end
end

