---
- hosts: guests
  pre_tasks:
    - name: Install prerequisits
      package:
        name:
          - git
          - ansible
        state: present
      become: yes
  roles:
    - role: "{{ role_name }}"

