# -*- mode: ruby -*-
# vi: set ft=ruby :

# Jedes Item dieses Arrays definiert den Namen, das Box Image und die Ansible 
# Gruppen einer Virtuellen Machine die zum testen der Rolle gestartet werden
# soll. In dieser Liste können je nach Bedarf Zeilen hinzugefügt oder entfernt
# werden. Der Rest des Vagrantfiles sollte nur angepasst werden müssen wenn man
# ein komplexeres Testszenario braucht.
guests = [
    { name: 'ubuntu', box: 'bento/ubuntu-17.04', groups: [] },
    { name: 'centos', box: 'centos/7',           groups: [] },
#   { name: 'debian', box: 'debian/testing64',   groups: [] },
#   { name: 'example1', box: 'centos/7', groups: ['web', 'mon'] },
#   { name: 'example2', box: 'centos/7', groups: ['db', 'mon'] },
]

# Hier können zusätzliche Ansible Gruppen für das von Vagrant erstellte Inventory
# angegeben werden. Die Gruppenzugehörigkeit von Clients sollte nicht hier
# sondern in der in der groups Liste in der Definition der VM festgelegt werden.
# So kann Vagrant die Namen mit denen die VMs erstellt werden selbst verwalten.
# Auch sollten, obwohl ich ihre Verwendung im Beispiel demonstriere,
# Gruppenvariablen besser in ein group_vars Verzeichnis ausgelagert werden.
# Siehe hierzu auch die Ansible Dokumentation:
# http://docs.ansible.com/ansible/latest/intro_inventory.html#splitting-out-host-and-group-specific-data
# Wenn man trotzdem Gruppenvariablen hier definiert, ist zu beachten, dass
# Booleans nur korrekt erkannt werden, wenn sie genau als 'True' und 'False'
# geschrieben sind.
ansible_groups = {
#   'web:children': ['db'],
#   'db:vars': { secure_setup: 'True' },
#   'mon:vars': { monitoring_server: 'mon.example.com', monitorin_port: '1234' },
}

# Bestimme den Namen des Moduls das zu testen ist aus dem Basename des Parent
# Directories des Directories in dem sich der Vagrantfile befindet
test_role = File.basename( File.absolute_path('..') )
ansible_groups.default = []

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Konfiguration aller Maschinen die in guests definiert sind
    guests.each_with_index do |guest, index|

        config.vm.define "#{test_role}-#{guest[:name]}" do |machine|
            machine.vm.hostname = "#{test_role}-#{guest[:name]}"
            machine.vm.box = guest[:box]
            # Jede Maschine bekommt eine IP im privaten Default Netzwerk von
            # Virtualbox, die sowohl von anderen VMs als auch vom Host aus
            # erreichbar ist. Für komplexere Tests sollte hier wahrscheinlich
            # trotzdem ein anderer Weg gewählt werden
            machine.vm.network 'private_network', type: 'dhcp'

            # Allgemeine Einstellungen die jede Maschine in Virtualbox bekommt.
            # Dieser Bereich kann an die Fähigkeiten des Hosts angepasst werden.
            machine.vm.provider 'virtualbox' do |vbox|
                vbox.name = "ansibe_#{test_role}_#{guest[:name]}"
                vbox.cpus = 2
                vbox.memory = 2048
            end

            guest[:groups].each do |group|
                ansible_groups[group] += ["#{test_role}-#{guest[:name]}"]
            end

            # Provisioniere, wenn die letzte Maschine hochgefahren wurde, alle
            # Maschinen mit Ansible. Würde dieser Block außerhalb einer einzigen
            # Maschinendefinition stehen, würde Ansible beim Hochfahren jeder
            # Maschine versuchen alle Maschinen zu konfigurieren
            if index == guests.size - 1
                machine.vm.provision 'ansible', run: 'always' do |ansible|
                    ansible.playbook = 'test.yml'
                    #ansible.verbose = 'vvvv'
                    #ansible.host_key_checking = false
                    ansible.limit = 'all'
                    ansible.become = false
                    ansible.groups = ansible_groups
                    ansible.extra_vars = {
                        test_role: test_role,
                    }
                end
            end
        end
    end
end

